"""expand telemetry for energy optimization

Revision ID: 1b74b539a715
Revises: 281c066c8554
Create Date: 2026-08-04 12:41:45.807707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b74b539a715'
down_revision: Union[str, Sequence[str], None] = '281c066c8554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('energy_consumption_kwh', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('solar_power_kw', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('solar_irradiance', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('battery_soc', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('battery_health', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('battery_status', sa.String(length=50), nullable=True))
    op.add_column('telemetry', sa.Column('battery_voltage', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('battery_current', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('battery_temperature', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('grid_available', sa.Boolean(), nullable=True))
    op.add_column('telemetry', sa.Column('grid_power_kw', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('grid_voltage', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('grid_frequency_hz', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('electricity_price', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('tariff_type', sa.String(length=50), nullable=True))
    op.add_column('telemetry', sa.Column('generator_available', sa.Boolean(), nullable=True))
    op.add_column('telemetry', sa.Column('generator_status', sa.String(length=50), nullable=True))
    op.add_column('telemetry', sa.Column('generator_power_kw', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('fuel_level', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('fuel_consumption_lph', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('power_source', sa.String(length=50), nullable=True))
    op.add_column('telemetry', sa.Column('equipment_status', sa.String(length=50), nullable=True))
    op.drop_column('telemetry', 'power')
    op.drop_column('telemetry', 'energy_consumption')
    op.drop_column('telemetry', 'voltage')
    op.drop_column('telemetry', 'current')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('current', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('telemetry', sa.Column('voltage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('telemetry', sa.Column('energy_consumption', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('telemetry', sa.Column('power', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('telemetry', 'equipment_status')
    op.drop_column('telemetry', 'power_source')
    op.drop_column('telemetry', 'temperature')
    op.drop_column('telemetry', 'fuel_consumption_lph')
    op.drop_column('telemetry', 'fuel_level')
    op.drop_column('telemetry', 'generator_power_kw')
    op.drop_column('telemetry', 'generator_status')
    op.drop_column('telemetry', 'generator_available')
    op.drop_column('telemetry', 'tariff_type')
    op.drop_column('telemetry', 'electricity_price')
    op.drop_column('telemetry', 'grid_frequency_hz')
    op.drop_column('telemetry', 'grid_voltage')
    op.drop_column('telemetry', 'grid_power_kw')
    op.drop_column('telemetry', 'grid_available')
    op.drop_column('telemetry', 'battery_temperature')
    op.drop_column('telemetry', 'battery_current')
    op.drop_column('telemetry', 'battery_voltage')
    op.drop_column('telemetry', 'battery_status')
    op.drop_column('telemetry', 'battery_health')
    op.drop_column('telemetry', 'battery_soc')
    op.drop_column('telemetry', 'solar_irradiance')
    op.drop_column('telemetry', 'solar_power_kw')
    op.drop_column('telemetry', 'energy_consumption_kwh')
    # ### end Alembic commands ###
